name: Weekly Exercise 2 Test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Test Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Codes
        uses: actions/checkout@v2
        
      - name: Checkout Test Scripts
        uses: actions/checkout@v2
        with:
          repository: Linus-Tay/JUnit_MAD_Exercise-2
          path: testDirectory
          
      - name: Check files
        run: |
            ls
            cd app
            cd src
            ls
            cd test
            cd java
            cd com
            cd example
            cd week2exercise
            ls
            
      - name: Create Test Files
        run: |
          cp testDirectory/Exercise_Test-2.kt app/src/test/java/com/example/week2exercise/
          cp testDirectory/MainActivity_Test.kt app/src/androidTest/java/com/example/week2exercise/

      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with: 
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test
        
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-results/**/*.xml

      - name: Build Project
        run: ./gradlew assemble
