name: Weekly Exercise 2 Test

on:
  push:
    branches: [master, main]

jobs:
  tests:
    name: Run Tests
    runs-on: macos-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v2
        
      - name: Checkout Test Scripts
        uses: actions/checkout@v2
        with:
          repository: Linus-Tay/JUnit_MAD_Exercise-2
          path: tests
            
      - name: Create Test Files
        run: |
          cp tests/Exercise_Test-2.kt app/src/test/java/com/example/week2exercise/UserTest.kt
          cp tests/MainActivity_Test.kt app/src/androidTest/java/com/example/week2exercise/MainActivityTest.kt

      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with: 
          java-version: 11

      - name: Make gradlew Executable
        run: chmod +x ./gradlew
        
      - name: Run Tests
        run: ./gradlew testDebugUnitTest

      - name: Run Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Report
          path: 
            ./app/build/reports/tests/testDebugUnitTest/*

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: Instrumentation Test Report
          path: 
            ./app/build/reports/androidTests/connected/*
