name: Weekly Exercise 2 Test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Test Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with: 
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Unit Test Results
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'