name: Weekly Exercise 2 Test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Test Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with: 
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: |
            app/src/androidTest/java/**/*.xml
            app/src/test/java/**/*.xml